name: Deployment v2
on: push
jobs:
  lint:
    runs-on: windows-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci
      - name: Lint
        run: npm run lint
  test:
    runs-on: windows-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci
      - name: Test code
        run: npm run test
  deploy:
    runs-on: windows-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci
      - name: Build code
        run: npm run build
      - name: Deploy code
        run: echo "Deploying..."